services:
  openlitespeed:
    build:
      context: .
      dockerfile: Dockerfile.ols
    container_name: ols-server
    ports:
      - "80:80"
      - "443:443"
      - "7080:7080"
    volumes:
      - ./config/ols/custom-conf:/usr/local/lsws/conf
      - ../:/var/www/html
      - ./config/ssl:/ssl
      - $HOME/letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    environment:
      - DEPLOY_ID=${DEPLOY_ID:-local}
    restart: always
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 30s
      timeout: 5s
      retries: 3
    mem_limit: 2g
    mem_reservation: 1g

networks:
  default:
    driver: bridge
