version: '3'

services:
  openlitespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: ols-server
    ports:
      - "80:80"
      - "443:443"
      - "7080:7080"
    volumes:
      - ./lsws-data:/usr/local/lsws
    environment:
      - TZ=Europe/Brussels
    restart: always
    networks:
      - app-network

  nextjs:
    build:
      context: ..
      dockerfile: .docker/nextjs.Dockerfile
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
