version: '3'

services:
  openlitespeed:
    image: litespeedtech/openlitespeed:latest
    volumes:
      - ./custom-conf:/usr/src/lsws-config
    entrypoint: [ "/usr/src/lsws-config/entrypoint.sh" ]
    command: [ "/entrypoint.sh" ]
    networks:
      - app-network

  nextjs:
    build:
      context: ..
      dockerfile: .docker/nextjs.Dockerfile
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
