services:
  openlitespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: openlitespeed
    volumes:
      - ./ols-config/templates:/etc/litespeed/templates
      - ./ols-config/vhosts:/etc/litespeed/vhosts
      - ./ols-config/init.sh:/usr/local/bin/init.sh
      - certbot-etc:/etc/letsencrypt:ro
      - ./volumes/webroot:/var/www/webroot
      - ..:/var/www/nextjs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Paris
    command: /usr/local/bin/init.sh
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./volumes/webroot:/var/www/webroot
    command: certonly --webroot --webroot-path=/var/www/webroot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}
    depends_on:
      - openlitespeed

  # Les autres services restent inchangés...

volumes:
  certbot-etc:
  certbot-var:
