name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate deployment ID
        id: deployment-id
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DEPLOY_ID="${VERSION}-${COMMIT_HASH}"
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV
          echo "Deployment ID: $DEPLOY_ID"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_ed25519
          if_key_exists: replace

      - name: Deploy to server
        run: |
          # Utiliser l'archive GitHub directement au lieu de créer un tar
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            # Télécharger l'archive directement sur le serveur
            cd /tmp && \
            curl -sL https://github.com/${{ github.repository }}/archive/${{ github.sha }}.tar.gz -o deploy-package.tar.gz && \
            # Exécuter le déploiement
            cd /home/hargile.eu/ && \
            bash .docker/scripts/deploy.sh ${{ env.DEPLOY_ID }}"

      - name: Verify deployment
        if: success()
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/hargile.eu/ && \
            bash .docker/scripts/healthcheck.sh"

      - name: Rollback if verification fails
        if: failure()
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/hargile.eu/ && \
            bash .docker/scripts/rollback.sh auto 'Déploiement échoué - Rollback automatique'"
